name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: Sortlizer-master

      - name: Run Flutter Analyze
        run: flutter analyze
        working-directory: Sortlizer-master

      - name: Run Flutter Tests
        run: flutter test
        working-directory: Sortlizer-master

      # --- Build Steps (We'll uncomment and add these in the next phase) ---
      # - name: Build Flutter Web
      #   run: flutter build web --release
      #   working-directory: Sortlizer-master

      # - name: Build Flutter Android (APK)
      #   run: flutter build apk --release
      #   working-directory: Sortlizer-master


      # --- Deployment Steps (These will come after successful builds) ---
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build/web
